<script src="frontend/angular.min.js"></script>
<script src="frontend/angular.util.js"></script>
<script src="frontend/jquery-3.6.3.min.js"></script>

<script src="frontend/jquery.loading.js"></script>
<link href="frontend/jquery.loading.css" type="text/css" rel="stylesheet" />
<script src="frontend/notify.min.js"></script>

<link rel="stylesheet" href="frontend/bootstrap.min.css">
<script src="frontend/bootstrap.min.js"></script>
<script src="frontend/jquery.mask.min.js" ></script>